#!/bin/sh /etc/rc.common
START=90
STOP=10

USE_PROCD=1

PROG="/root/ifremer/python/loraship_start.sh"

PIDFILE=/var/run/loraship_mqtt_sub.pid

start_service() {
        echo start service
        # commands to launch application
        procd_open_instance
        procd_set_param command /bin/sh $PROG
        # procd_set_param stdout 1
        # procd_set_param stderr 1
        procd_set_param pidfile $PIDFILE
        # procd_set_param user nobody
        procd_close_instance
}

stop_service() {
        echo stop service
        # commands to kill application
}


