#!/bin/sh /etc/rc.common
START=90
STOP=10

USE_PROCD=1

PROG="/root/ifremer/python/loraship_start.sh"

PIDFILE=/root/ifremer/python/loraship_start.pid

start_service() {
        echo start loraship service
        # commands to launch application
        procd_open_instance
        procd_set_param command /bin/sh $PROG
        # procd_set_param stdout 1
        # procd_set_param stderr 1
        procd_set_param pidfile $PIDFILE
        # procd_set_param user nobody
        procd_close_instance
}

stop_service() {
        echo stop loraship service
        # commands to kill application
        # get PID of child processes running the python scripts that have been started with loraship_start.sh
        echo will kill process with PID stored in mqtt_sub.pid if exists
        cat /root/ifremer/python/mqtt_sub.pid | xargs kill -15
        rm /root/ifremer/python/mqtt_sub.pid
        echo done
}

reload_service() {
        echo reload loraship service
        stop
        start
}



